import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("org.gradle.samples.")) {
                useModule("org.gradle.samples.plugins:plugins:1.0")
            }
        }
    }
}

include("samples-dev")

includeBuild("samples-dev/plugins")
includeBuild("samples-dev/src/templates/custom-publication-plugin")
includeBuild("samples-dev/src/templates/build-wrapper-plugin")
includeBuild("samples-dev/src/templates/release-plugin")

rootProject.name = 'native-samples'

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    repositories {
        mavenCentral()
    }
}
