plugins {
    id 'java-gradle-plugin'
}

gradlePlugin {
    plugins {
        externalBuildsBase {
            id = 'dev.nokee.samples.external-builds-base'
            implementationClass = 'dev.nokee.samples.externalbuilds.ExternalBuildsBasePlugin'
        }
    }

    dependencies {
        implementation 'com.google.guava:guava:27.1-jre'
    }
}