name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare
        run: ./gradlew :prepare --init-script sample.init.gradle

      - name: Build with Gradle
        run: ./gradlew :samples-dev:test --init-script sample.init.gradle
